# --build-arg BROWSER="chrome"

run tests:
  script: -|
    source .venv/bin/activate
    behave --no-capture -f allure_behave.formatter:AllureFormatter -o results
    deactivate
  artifacts:
    when: always
    paths: -|
      reports/
      results/